[move-lang][tests] remove the stale ir-coverage test
Tests migration in #8948 leaves a few non-existing directories in the
ir-testsuite, which the `ir_coverage_test` complains about, e.g.,

```
thread 'test_ir_test_coverage' panicked at 'Invalid completed directory.
'../ir-testsuite/tests/move/borrow_tests' does not exist',
language/move-lang/tests/ir_test_coverage.rs:14:13
```

Under the new transactional testing system, every test should ideally
reside with the component it targets to test. In addition, the move
source comiler has accumulated a fairly robust set of test cases, we
can delete this test case as it is extremely hard to maintain it with
the new transactional testing infra.